/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package projectsoftt.gui;

import javax.swing.JOptionPane;
import projectsoftt.quiz.Question;
import projectsoftt.quiz.QuestionFactory;
import projectsoftt.quiz.QuizManager;

/**
 *
 * @author M.osman
 */
public class ManagerFrame extends javax.swing.JFrame {

    /** Creates new form ManagerFrame */
    public ManagerFrame() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        managerquiz = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        managerquiz.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        managerquiz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsoftt/gui/icons8-create-100.png"))); // NOI18N
        managerquiz.setText("Create Quiz and Start");
        managerquiz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerquizActionPerformed(evt);
            }
        });
        getContentPane().add(managerquiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 510, 330, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectsoftt/gui/OIP (5) (1).jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void managerquizActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerquizActionPerformed

         QuizManager manager = QuizManager.getInstance();
    JOptionPane.showMessageDialog(
        null,
        "Exam is now available.",
        "Success",
        JOptionPane.INFORMATION_MESSAGE
    );
    }//GEN-LAST:event_managerquizActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton managerquiz;
    // End of variables declaration//GEN-END:variables

}
